#FROM java:8-alpine
#LABEL maintainer=""

#RUN echo -e "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/main\n\
#https://mirror.tuna.tsinghua.edu.cn/alpine/v3.4/community" > /etc/apk/repositories

#RUN apk --update add curl bash ttf-dejavu && \
#      rm -rf /var/cache/apk/*

#COPY entrypoint.sh /entrypoint.sh
#RUN chmod +x /entrypoint.sh
#ENTRYPOINT "/entrypoint.sh"
