version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts       
    container_name: jenkins-server
    environment:
      - TZ=Asia/Shanghai
    restart: always
    user: root
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - ./data/:/var/jenkins_home
      - /home/maven:/home/maven
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./ssh:/root/.ssh
      
