
global:
  scrape_interval:     15s
  evaluation_interval: 15s
 
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
 
rule_files:
  - "*rules.yml"
 
scrape_configs:
 
  - job_name: 'node_prom_localhost'
    static_configs:
    - targets: ['192.168.200.108:9200']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080'] 
  - job_name: 'alertmanager'
    static_configs:
    - targets: ['alertmanager:9093']
  - job_name: 'paperless'
    static_configs:
    - targets: ['192.168.7.210:8088']
  - job_name: 'dynamicdata'
    static_configs:
    - targets: ['192.168.11.121:8088']           
  - job_name: 'jurisdiction'
    static_configs:
    - targets: ['192.168.7.210:8089']
