version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./db:/data/db
      - ./log:/var/log/mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
#      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongodb:27017/