version: "3"

services:
    nacos1:
        container_name: nacos-server01
        hostname: nacos-server01
        image: nacos/nacos-server:2.0.3
        environment:
            - MODE=cluster
            - PREFER_HOST_MODE=hostname
            - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
            - SPRING_DATASOURCE_PLATFORM=mysql
            - MYSQL_SERVICE_HOST=192.168.200.109
            - MYSQL_SERVICE_PORT=3306
            - MYSQL_SERVICE_USER=root
            - MYSQL_SERVICE_PASSWORD=123457
            - MYSQL_SERVICE_DB_NAME=nacos_config nacos数据库
            - JVM_XMS=128m
            - JVM_XMX=128m
            - JVM_XMN=128m
        volumes:
            - ./cluster-logs/nacos1:/home/nacos/logs
            - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
        ports:
            - 8848:8848
        restart: on-failure

    nacos2:
        container_name: nacos-server02
        hostname: nacos-server02
        image: nacos/nacos-server:2.0.3
        environment:
            - MODE=cluster
            - PREFER_HOST_MODE=hostname
            - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
            - SPRING_DATASOURCE_PLATFORM=mysql
            - MYSQL_SERVICE_HOST=192.168.120.253
            - MYSQL_SERVICE_PORT=3306
            - MYSQL_SERVICE_USER=root
            - MYSQL_SERVICE_PASSWORD=root
            - MYSQL_SERVICE_DB_NAME=nacos_config
            - JVM_XMS=128m
            - JVM_XMX=128m
            - JVM_XMN=128m
        volumes:
            - ./cluster-logs/nacos1:/home/nacos/logs
            - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
        ports:
            - 8849:8848
        restart: on-failure

    nacos3:
        container_name: nacos-server03
        hostname: nacos-server03
        image: nacos/nacos-server:2.0.3
        environment:
            - MODE=cluster
            - PREFER_HOST_MODE=hostname
            - NACOS_SERVERS=nacos-server01:8848 nacos-server02:8848 nacos-server03:8848
            - SPRING_DATASOURCE_PLATFORM=mysql
            - MYSQL_SERVICE_HOST=192.168.120.253
            - MYSQL_SERVICE_PORT=3306
            - MYSQL_SERVICE_USER=root
            - MYSQL_SERVICE_PASSWORD=root
            - MYSQL_SERVICE_DB_NAME=nacos_config
            - JVM_XMS=128m
            - JVM_XMX=128m
            - JVM_XMN=128m
        volumes:
            - ./cluster-logs/nacos1:/home/nacos/logs
            - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
        ports:
            - 8850:8848
        restart: on-failure