spring:
  application:
    name: oauth-server
  redis:
    lettuce:
      pool:
        max-active: 8
    host: zxw.middleware.com
    port: 16379
    password: znw@123
    database: 7
  #    cluster:
  #      nodes: redis.dev.magpie.com:7001,redis.dev.magpie.com:7002,redis.dev.magpie.com:7003
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://zxw.middleware.com:3306/dd_text?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Admin!@123
  data:
    mongodb:
      uri: mongodb://zxw.middleware.com:27017/magpie_test?maxIdleTimeMS=3000
  kafka:
    bootstrap-servers: zxw.middleware.com:9092
    producer:
      acks: 1
      client-id: kafka-producer
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0
    consumer:
      group-id: hello-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  rabbitmq:
    host: zxw.middleware.com
    port: 5672
    username: zhuxw
    password: 123456
    virtual-host: /apec
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 250
  messages:
    basename: i18n/app
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
rocketmq:
  name-server: zxw.middleware.com:9876
  producer:
    group: my-producer-group
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
storage:
  ribbon:
    #建立连接超时时间
    ConnectTimeout: 6000
    #建立连接之后，读取响应资源超时时间
    ReadTimeout: 6000
    MaxAutoRetries: 3
    MaxAutoRetriesNextServer: 3

feign:
  httpclient:
    enabled: true
  client:
    config:
      storage:
        connect-timeout: 5000
        ReadTimeout: 5000
        MaxAutoRetries: 2
        MaxAutoRetriesNextServer: 2

#logging:
#  config: classpath:logback-spring.xml
#  thymeleaf:
#    enabled: true  #开启thymeleaf视图解析
#    encoding: utf-8  #编码
##    prefix: classpath:/templates/  #前缀
#    cache: false  #是否使用缓存
#    mode: HTML  #严格的HTML语法模式
#    suffix: .html  #后缀名
server:
  port: 8082
logging:
  config: classpath:logback-spring.xml
bean:
  key: 123
  map:
    key: 123
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method
    #custom path for api docs
    url: /doc/openapi.json
cf:
  jwt:
    keyPairName: jwt.jks
    keyPairAlias: jwt
    keyPairSecret: 123123
    keyPairStoreSecret: 123123
#--spring:
#  profiles:
#    active=chaos-monkey:
#chaos:
#  monkey:
#    # 启动monkey
#    enabled: true
#    assaults:
#      # 确定多少请求被攻击，1为攻击所有请求；5：每5个请求攻击一次
#      level: 1
#      # 增加最小延时，毫秒
#      latency-range-start: 5000
#      # 增加最大延时，毫秒
#      latency-range-end: 10000
#      # 延时攻击启动
#      latency-active: true
#      # 异常攻击启动
#      exceptions-active: true
#      # kill应用启动
#      kill-application-active: true
#    watcher: # 控制范围
#      controller: true
#      rest-controller: true
#      service: true
#      repository: true # （JDBC和JPA）
#      component: true