version: "3"
services:
    redis:
        image: redis:5.0.10-alpine
        container_name: redis-single-server
        command: redis-server /usr/local/etc/redis/redis.conf
        restart: always
        ports:
            - 16379:6379
        volumes:
            - ./data:/data
            - ./conf/redis.conf:/usr/local/etc/redis/redis.conf